Fitur_1/urls.py
from django.conf.urls import url
from .views import index, add_todo

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_status', add_todo, name='add_todo'),
]

TP_PPW/urls.py
from django.views.generic import RedirectView
from django.conf.urls import url, include
from django.contrib import admin
import app_stats.urls as app_stats
import Fitur_1.urls as Fitur_1
import add_friend.urls as add_friend
import profiles.urls as profile
urlpatterns = [
    url(r'^$', RedirectView.as_view(url ='/dashboard/', permanent = True), name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^dashboard/', include(app_stats, namespace='app_stats')),
    url(r'^status/', include(Fitur_1, namespace='Fitur_1')),
    url(r'^add_friend/', include(add_friend, namespace='add_friend')),
    url(r'^profile/',include(profile, namespace='profile')),
]

add_friend/urls.py
from django.conf.urls import url
from .views import index, adding_friend

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^add_friend', adding_friend, name='add_friend'),
	]

app_stats/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
]

profiles/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
]

Fitur_1/models.py
from django.db import models

class Todo(models.Model):
    description = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

add_friend/models.py
from django.db import models
from django.utils import timezone
import pytz

class Friends(models.Model):
	name = models.CharField(max_length=27)
	url = models.URLField()
	created_date = models.DateTimeField(auto_now_add=True)

app_stats/models.py
from django.db import models

# Create your models here.

profiles/models.py
from django.db import models


# Create your models here.
class Profile(models.Model):
    profile_pic = models.URLField(default="https://www.lausanne.org/wp-content/uploads/2017/04/anonymous-icon-150x150.jpg")
    name = models.CharField(max_length=27)
    birthday = models.CharField(max_length=6, default='01 Jan')
    gender = models.CharField(max_length=10)
    expertise = models.ManyToManyField('Expertise')
    description = models.CharField(max_length=27)
    email = models.EmailField()


class Expertise(models.Model):
    expertise = models.CharField(max_length=27)

    def __str__(self):
        return str(self.expertise)

Fitur_1/forms.py
from django import forms

class Todo_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }
    description_attrs = {
        'type': 'text',
        'cols': 148,
        'rows': 4,
        'class': 'todo-form-textarea',
        'placeholder':'Masukan status baru...'
    }

    description = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=description_attrs))

add_friend/forms.py
from django import forms

class Add_Friend(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
        'invalid': 'Isi input dengan URL',
    }
    name_attrs = {
    	'type' : 'text',
        'class': 'form-control'
    }
    url_attrs = {
    	'type' : 'URL',
    	'class' : 'form-control'
    }

    name = forms.CharField(label='Name', required=True, max_length=27, widget=forms.TextInput(attrs=name_attrs))
    URL = forms.URLField(label='URL',required=True, widget=forms.TextInput(attrs=url_attrs))

Fitur_1/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Todo_Form
from .models import Todo
from profiles.views import name

# Create your views here.
response = {}
def index(request):
    response['author'] = "Luthfi Dzaky, Nurdela Ardiansyah, Haikal Ravendy, M. Sulthan Rafi S." #TODO Implement yourname
    todo = Todo.objects.all()
    response['name']=name
    response['todo'] = todo
    html = 'fitur_1/fitur_1.html'
    response['todo_form'] = Todo_Form
    return render(request, html, response)

def add_todo(request):
    form = Todo_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['description'] = request.POST['description']
        todo = Todo(description=response['description'])
        todo.save()
        return HttpResponseRedirect('/status/')
    else:
        return HttpResponseRedirect('/status/')

add_friend/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Add_Friend
from .models import Friends

# Create your views here.

response = {}


def index(request):
    response['Add_Friend'] = Add_Friend
    response['author'] = "Luthfi Dzaky, Nurdela Ardiansyah, Haikal Ravendy, M. Sulthan Rafi S."
    # TODO Implement, isilah dengan 6 kata yang mendeskripsikan anda
    my_friend = Friends.objects.all()
    response['my_friend'] = my_friend
    html = 'add_friend/add_friend.html'
    return render(request, html, response)


def adding_friend(request):
    form = Add_Friend(request.POST or None)
    if (request.method == 'POST' and form.is_valid()):
        response['name'] = request.POST['name']
        response['URL'] = request.POST['URL']
        my_friend = Friends(name=response['name'], url=response['URL'])
        my_friend.save()
        html = 'add_friend/add_friend.html'
        return HttpResponseRedirect('/add_friend/')
    else:
        return HttpResponseRedirect('/add_friend/')

app_stats/views.py
from django.shortcuts import render
from add_friend.models import Friends
from Fitur_1.models import Todo
from profiles.views import name

# Create your views here.
response = {}

def index(request):
    response['laststatus']=''
    response['created_date'] = ''
    response['name'] = name
    friend = Friends.objects.all().count();
    feeds = Todo.objects.all().count();
    if(feeds>0):
        status= Todo.objects.all().order_by('-created_date')[0]
        response['laststatus']=status.description
        response['created_date']=status.created_date
    response['author']= "Luthfi Dzaky, Nurdela Ardiansyah, Haikal Ravendy, M. Sulthan Rafi S."
    response['friend']=friend
    response['feeds']=feeds
    html = 'app_stats/app_stats.html'
    return render(request,html,response)

profiles/views.py
from django.shortcuts import render
from .models import Profile, Expertise


# Create your views here.
response = {}
name = 'Hepzibah Smith'
def index(request):
    # Create a new profile
    count_all_profiles = Profile.objects.count()

    # if count_all_profiles == 0:
    profile = Profile.objects.create(
        profile_pic='https://pre00.deviantart.net/19f7/th/pre/f/2014/097/2/0/nyanko_sensei__dinner_s_ready__by_oboeteru-d7djql9.png',
        name='Hepzibah Smith', birthday='12 Oct', gender='Male',
        description='A stressed overachiever.', email='spence@hastings.com')
    profile.save()

    e1 = Expertise.objects.create(expertise='Fun Coding')
    e1.save()
    e2 = Expertise.objects.create(expertise='Modeling')
    e2.save()
    e3 = Expertise.objects.create(expertise='Taking Tests')
    e3.save()

    profile.expertise.add(e1)
    profile.expertise.add(e2)
    profile.expertise.add(e3)
    # else:
    #     profile = Profile.objects.last()

    # Inserting profile aspects into response
    response['profile_pic'] = profile.profile_pic
    response['name'] = profile.name
    response['birthday'] = profile.birthday
    response['gender'] = profile.gender
    response['expertise'] = profile.expertise.all()
    response['description'] = profile.description
    response['email'] = profile.email

    # Specifying html

    response['author'] = "Luthfi Dzaky, Nurdela Ardiansyah, Haikal Ravendy, M. Sulthan Rafi S."
    # response['name'] = name
    html = 'profiles/profiles.html'
    # response['about_me'] = about_me

    return render(request, html, response)

Fitur_1/templates/fitur_1/fitur_1.html
{% extends "base.html" %}

{% block content %}
<section name="input-list" id="input-list">
    <div class="container">
        <form class="post-status" id="form" method="POST" action="{% url 'Fitur_1:add_todo' %}">
            <h2 style="color:white;">Update Status</h2>
            {% csrf_token %}
            {{ todo_form }}
            <input id="submit" type="submit" class="btn btn-lg btn-primary pull-right btn-info" value="Post">
        </form>
    </div>
</section>
<section name="my-list" id="my-list">
    <div class="container">
        <div class="flex">
            {% if todo %}
            <h2 class="page-header">Status</h2>
                {% for data in todo %}
                    <article class="row">
                        <div class="col-md-2 col-sm-2 hidden-xs">
                          <figure class="thumbnail">
                            <img class="img-responsive" src="http://zdnet3.cbsistatic.com/hub/i/2014/09/18/a2bf8b11-3f23-11e4-b6a0-d4ae52e95e57/f556a234d5e5ece266af47828ec8665c/your-company-doesnt-own-your-internet-presence.png" />
                            <figcaption class="text-center post-status">{{ name }}</figcaption>
                          </figure>
                        </div>
                        <div class="col-md-10 col-sm-10">
                          <div class="panel panel-default arrow left">
                            <div class="panel-body post-status">
                              <header class="text-left">
                                <div class="comment-user"><i class="fa fa-user"></i>{{ name }}</div>
                              </header>
                              <div class="comment-post">
                                <p>
                                  {{data.description}}
                                </p>
                              </div>
                              <time class="comment-date" datetime="16-12-2014 01:05"><i class="fa fa-clock-o"></i> {{data.created_date}}</time>
                            </div>
                          </div>
                        </div>
                      </article>
                                
                {% endfor %}
            {% endif %}
        </div>
    </div>
</section>

{% endblock %}

add_friend/templates/add_friend/add_friend.html
{% extends "base.html" %}

    {% block content %}
    <section name="form">
        <h2><u>Add Friend</u></h2>
        <form id="form" method="POST" action="{% url 'add_friend:add_friend' %}">
            {% csrf_token %}
            {{ Add_Friend }}
            <br>
            <button type="submit" class="btn btn-default" style="float: right; background: lightgray;border-color: black">Add Friend</button>
        </form>
    </section>

    <section name="table teman">
        <!--  Populate semua isi pesan dari model -->
        <table class="table" style="table-layout: fixed;">
            <thead">
                <th style="border:0 none">List Friend</th>
            </thead>
            <tbody style="border:0 none">
                {% for i in my_friend %}
                    <td style="border:0 none; text-align: left"> {{i.name}} </td>
                    <td style="border:0 none; "><a href=" {{i.url}}">{{i.url}}</td>
                    <td style="border:0 none; text-align: right"><i> Added {{i.created_date}} </i></td>
                </tr>             
                {% endfor %}
            </tbody>
        </table>
    </section>

    {% endblock %}

add_friend/templates/add_friend/layout/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="description" content="Add Friend">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">    

    <title> 
        {% block title %} Designed by {{author}}{% endblock %}
    </title>
</head>

<body style="background-color: lightgray">
    <!-- disini header kali ya pi-->
    <content>
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>

    </content>
    <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        <!-- buat lutpi isi footer-->
        {% endblock %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

app_stats/templates/app_stats/app_stats.html
{% extends "base.html" %}
{% block content %}

<link rel="stylesheet" id="tt-easy-google-fonts-css" href="https://fonts.googleapis.com/css?family=Open+Sans%3Aregular%7CMuli%3Aregular%2C300&amp;subset=latin%2Call%2Call&amp;ver=4.7.6" type="text/css" media="all">

<style>
        .image-atas {
        width:165px;
        height:160px;
        border-style: hidden;
        border-radius: 100%;
        float:left;
        margin-left:140px;
    }
    .image-atas:hover{
        width:185px;
        height:180px;
    }

    .image-bawah{
        width:50px;
        height:40px;
        border-style: hidden;
        margin-top:15px;
        margin-left:60px;
        float:left;
    }
    .nama-atas{
        margin-top: 60px;
        padding-left: 340px;
        margin-top: 66px;
        padding-left: 350px;
    }
    .nama-bawah{
        margin-top: 40px;
        margin-left:20px;
        padding-left: 100px;
    }
    .position{
        margin-left:100px;
    }
    .friendss{
        padding-left:60px;
    }
    #post{
       padding-left:600px;
       }

    .friendss:hover, #post:hover{
        font-size:20px;
    }
    #post{
       padding-left:750px;
       }
    #slash{
    padding-left:300px;
    float:left;
    }
     body{
     font-family: 'Muli';
    background: linear-gradient(180deg, #35577D, #141E30) no-repeat;
    color:white;
     }
     #statistic{
    text-align: center;
    font-size:40px;
    letter-spacing:4px;
  }

</style>
<head>
    <meta charset="UTF-8">
    <title>Statistic</title>
</head>
<body>
    <h1 id="statistic"><strong>Statistic of {{ name }}</strong></h1>
</div>
<hr class="container" style="width: 1000px"/>
<br></br>

<div class="container">
    <img class="image-atas" alt="Luthfi Dzaky"
         src="http://zdnet3.cbsistatic.com/hub/i/2014/09/18/a2bf8b11-3f23-11e4-b6a0-d4ae52e95e57/f556a234d5e5ece266af47828ec8665c/your-company-doesnt-own-your-internet-presence.png">
    <h2 class="nama-atas"><strong>{{ name }}</strong></h2>
</div>

<br></br>

<section>
<div class="container position">
    <h4 class="friendss" style="float:left"><a href="/add_friend/"><strong>Friends </strong></a> {{ friend }} People</h4>
    <h4 id="slash">|</h4>
    <h4 id="post"><a href="/status/"><strong>Feed </strong></a> {{feeds}} Post</h4>
</div>
</section>
<hr class="container" style="width: 1000px"/>
<br></br>

<div class="container position">
    <h4 class="friendss"><strong>Latest Post</strong></h4>
    <img class="image-bawah" alt="Luthfi Dzaky"
         src="http://zdnet3.cbsistatic.com/hub/i/2014/09/18/a2bf8b11-3f23-11e4-b6a0-d4ae52e95e57/f556a234d5e5ece266af47828ec8665c/your-company-doesnt-own-your-internet-presence.png">
    <h4 class="nama-bawah"><strong>{{ name }}</strong></h4>
</div>

<div class="container position" style="width:400px">
    <h5 style="margin-left:60px">{{ laststatus }}</h5>
    <h6 style="color: lightgray; margin-left:60px;">{{ created_date }}</h6>
</div>

<br></br>
</body>
{% endblock %}

app_stats/templates/app_stats/layout/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" id="tt-easy-google-fonts-css" href="https://fonts.googleapis.com/css?family=Open+Sans%3Aregular%7CMuli%3Aregular%2C300&amp;subset=latin%2Call%2Call&amp;ver=4.7.6" type="text/css" media="all">
</head>
<style>
footer p{
        text-align: center;
        padding-top:10px;
    }</style>
<body>
<header>
    {% include "app_stats/partials/header.html" %}
</header>
<br></br>

<br></br>
<content>
    {% block content %}
    <!-- content goes here -->
    {% endblock %}
</content>
<footer>
    <!-- TODO Block Footer dan include footer.html -->
    {% block footer %}
    {% include "app_stats/partials/footer.html" %}
    {% endblock %}
</footer>
</body>
</html>

app_stats/templates/app_stats/partials/footer.html
<p>&copy; Our Team {{author}}</p>

app_stats/templates/app_stats/partials/header.html
<nav class="navbar navbar-inverse navbar-fixed-top" id="navbar-top">
  <div class="container-fluid"  >
    <div class="navbar-header">
      <a class="navbar-brand" href="#"><strong>Ling in</strong></a>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="/status/">Status</a></li>
      <li><a href="/profile/">Profile</a></li>
      <li><a href="/add_friend/">Friends</a></li>
      <li><a href="/dashboard/">Stats</a></li>
    </ul>
  </div>
</nav>

profiles/templates/profiles/edit.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/profile.css' %}">
{% endblock %}

{% block content %}
    <form action="/action_page.php">
      Birthday:<br>
      <input type="text" name="birthday" ><br>
      Gender:<br>
      <input type="text" name="gender"><br><br>
      Expertise:<br>
      <input type="text" name="expertise"><br><br>
      Description:<br>
      <input type="text" name="description"><br><br>

      <input type="submit" value="Submit">
      <input type="reset">
    </form>
{% endblock %}

profiles/templates/profiles/profiles.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/profile.css' %}">
{% endblock %}

{% block content %}

    <h1> PROFILE PAGE </h1>
    <div id="profile_picture">
        <div align="center"><img class="img-circle" height="180px" width="185px" src="{{ profile_pic }}" class="center"></div>
    </div>
    <div id="name">
     <div align="center">{{ name }}</div>
    </div>
    <div id="bio">
    <table align="center">
        <tr>
            <td id="subject">Birthday</td>
            <td id="value">{{ birthday }}</td>
        </tr>
        <tr>
            <td id="subject">Gender</td>
            <td id="value">{{ gender }}</td>
        </tr>
        <tr>
            <td id="subject">Expertise</td>
            <td id="value">{% for object in expertise %}
                <div class = "expertise">{{ object }}</div>
            {% endfor %}</td>
        </tr>
        <tr>
            <td id="subject">Description</td>
            <td id="value">{{ description }}</td>
        </tr>
        <tr>
            <td id="subject">Email</td>
            <td id="value">{{ email }}</td>
        </tr>
    </table>
  
    </div>
{% endblock %}

templates/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block css %}
    {% endblock %}
    <meta charset="UTF-8">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
     <link rel="stylesheet" id="tt-easy-google-fonts-css" href="https://fonts.googleapis.com/css?family=Open+Sans%3Aregular%7CMuli%3Aregular%2C300&amp;subset=latin%2Call%2Call&amp;ver=4.7.6" type="text/css" media="all">
</head>
<body>
<style>
textarea {
   resize: none;
}
body{
    font-family: 'Muli';
    background: linear-gradient(180deg, #35577D, #141E30) no-repeat fixed 0 100%;
    color:white;
    margin-left: 5%;
    margin-right: 5%;
        }
    .post-status{
    color:black;}

    footer p{
        text-align: center;
        padding-top:10px;
    }
</style>
<header>
    {% include "app_stats/partials/header.html" %}
</header>
<br></br>

<br></br>
<content>
    {% block content %}
    <!-- content goes here -->
    {% endblock %}
</content>
<footer>
    <!-- TODO Block Footer dan include footer.html -->
    {% block footer %}
    {% include "app_stats/partials/footer.html" %}
    {% endblock %}
</footer>
</body>
</html>

templates/footer.html
<p>&copy; Our Team {{author}}</p>

templates/header.html
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <!-- LINK MENUJU table, dan link menuju home#form -->
        <li><a href="/lab-5/#input-list">Input Todo</a></li>
        <li><a href="/lab-5/#my-list">My Listads</a> </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>